### ISSUE TITLE
plotPhylonet issue

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks#11]
For these two examples, the plot presents each edge twice. It is not a problem with the root placement because this is not a network, it is a tree, so it should work regardless of the root position.
 (((Scer,Spar),Smik,Skud),Sbay);
(((Scer,Spar),Skud,Sbay),Smik);

![screen shot 2015-08-17 at 11 47 08 am](https://cloud.githubusercontent.com/assets/8419800/9310535/e5d32aa2-44d5-11e5-8dee-0c9a8ed8c047.png)

**Comment by cecileane** [comment]
I think I fixed the bug: in drawTraversal.jl, the number for the root was wrongly taken as the index of the root node in the network's list of nodes. But with the change to julia v0.4, I am having trouble compiling GraphViz. So I could only check that the .dot files looked bug-free. I could not get GraphViz to produce the image from the .dot file.

**Comment by crsl4** [comment]
Things work for me, thanks Cecile, I will close now!
