### ISSUE TITLE
readTableCF error: UndefVarError: DEBUG not defined

### ISSUE THREAD

**Issue by ikkyle** [crsl4/PhyloNetworks#19]
I'm trying to convert a DataFrame to a DataCF type. I've tried via 

``` julia 
cf = readTableCF("data/quartetCF.csv")
``` 

and

``` julia
dat = readtable("data/quartetCF.csv")
cf = readTableCF(dat)
```

Both the calls to `readTableCF` return the error: 

```
ERROR: UndefVarError: DEBUG not defined
 in readTableCF at /home/ikkyle/.julia/v0.4/PhyloNetworks/src/readData.jl:41
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68
```

This is using a version of PhyloNetworks as of a couple hours ago and Julia 0.4.0 prerelease

**Comment by crsl4** [comment]
Have you tried directly: cf = readTableCF("data/quartetCF.csv") (without the intermediate step)?

**Comment by crsl4** [comment]
Also, have you pulled recently? For version 0.4 you should be using file readData2.jl (not readData.jl), a quick fix that I did to be able to use version 0.4, I will *not* keep two files (readData.jl, readData2.jl) for sure, I just created readData2.jl for version 0.4 to see if few changes would make the code run in 0.4 (which it does).

**Comment by crsl4** [comment]
Look at PhyloNetworks.jl for details on the files to include if you are not doing "using PhyloNetworks"

**Comment by crsl4** [comment]
One last thing (sorry for the million messages), if you are not doing "using PhyloNetworks" at the beginning, you should do include(".../src/types.jl") and include(.../src/functions.jl) because they define the constant DEBUG

**Comment by ikkyle** [comment]
I pulled PhyloNetworks today and have been on version 0.4 for awhile. I'm doing `using PhyloNetworks` and have tried  `cf = readTableCF("data/quartetCF.csv")` directly as well. Same error. 

I also get a warning when I load PhyloNetworks that says

``` 
WARNING: deprecated syntax "[a=>b, ...]" at /home/ikkyle/.julia/v0.4/PhyloNetworks/src/optimization.jl:6.
Use "Dict(a=>b, ...)" instead.
```

I'm not sure that would be an issue because I think the depreciated syntax still works for now.

**Comment by ikkyle** [comment]
Whoops. Just updated to the stable version of 0.4.0 and it all works now. Sorry about the confusion.
