### ISSUE TITLE
plotPhylonet bug

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks#20]
I tried to add plotPhylonet in the README file, but when running the steps in the readme file and trying to plot net1 at the end, I got an error and actually, I was kicked out of julia altogether!
I did changes to plotPhylonet to update to version 0.4, but they only involved change String to AbstractString.

**Comment by crsl4** [comment]
Update: it seems that the .dot file was created, but I don't know if it is correct. The svg file was not created.

**Comment by cecileane** [comment]
`plotPhylonet` was replaced by `plot`, now based on the Gadfly package.
