### ISSUE TITLE
returnNet unused in optTopRun1!

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks#36]
modify line 1400 of `optimization.jl` from this
```
best = optTopLevel!(currT, M, Nfail, d, hmax,ftolRel, ftolAbs, xtolRel, xtolAbs, verbose, closeN , Nmov0,true,sout,logfile)
```
to this below?
```
best = optTopLevel!(currT, M, Nfail, d, hmax,ftolRel, ftolAbs, xtolRel, xtolAbs, verbose, closeN , Nmov0,returnNet,sout,logfile)
```

**Comment by crsl4** [comment]
Thanks Cecile!
Yes, I fixed this.
I still need to modify this, because the function returns a different type depending returnNet, but for now, it is fine like this.
