### ISSUE TITLE
writeTopology

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks#37]
issue found when the root is a leaf, the leaf is not printed in the parenthetical format. The nodes and edges are correctly attached.
```julia
n = "(1,(((6,5):1.516,(3,(4)#H7:::0.715):0.507):1.453,2):10.0,#H7:::0.285);"
net =readTopologyLevel1(n)
tree = majorTree(net)
printEdges(tree)
printNodes(tree)
writeTopology(tree) 
```
((((6:1.0,5:1.0):1.516,(3:1.0,4:2.0):0.507):1.453,2:1.0):10.0);  taxon 1 is missing!
```julia
tree.root
``` 
1

If we change the root, the parenthetical format is correct again:
```julia
tree.root=4
writeTopolology(tree)
```
(6:1.0,5:1.0,((3:1.0,4:2.0):0.507,(2:1.0,1:10.0):1.453):1.516);

**Comment by cecileane** [comment]
This is now fixed. I get this:
```julia
n = "(1,(((6,5):1.516,(3,(4)#H7:::0.715):0.507):1.453,2):10.0,#H7:::0.285);"
net =readTopologyLevel1(n)
tree = majorTree(net)
writeTopology(tree)
```
taxon 1 does appear now: `"(((6:1.0,5:1.0):1.516,(3:1.0,4:2.0):0.507):1.453,2:1.0,1:11.0);"`.
We see it with `plot(tree)` as well. Reading in with `readTopology` instead of `readTopologyLevel1` works too.
```julia
net =readTopology(n)
tree = majorTree(net)
writeTopology(tree) # "(((6,5):1.516,(3,4):0.507):1.453,2,1);"
plot(tree) # works too.
```
